"""Generate data/shop.db: a synthetic, scaled-up Lumi Skin shop (seed 42).

    python -m shop_data_mcp.generate_data            # writes data/shop.db
    python -m shop_data_mcp.generate_data --out x.db

Everything is invented. The 40 products come from the shared Lumi Skin catalogue
(data/lumi_skin/products.csv, "shared synthetic Lumi Skin data, generated by
generate.py (seed 42)"). The name pools are copied from that same generator.
Customers, orders, returns and reviews are generated here at a larger scale:
2,000 customers and about 5,000 orders from April 2025 to September 2026.

Only the Python standard library is used, so the same seed gives the same
database on every machine (a test checks this against the stored gold answers).
"""

import argparse
import csv
import random
import sqlite3
import unicodedata
from datetime import date, timedelta
from pathlib import Path

from shop_data_mcp import config

SEED = 42
START = date(2025, 4, 1)
SNAPSHOT = date(2026, 9, 30)  # the data is a snapshot taken at the end of this day
N_CUSTOMERS = 2000
PRODUCTS_CSV = config.REPO_ROOT / "data" / "lumi_skin" / "products.csv"

# Name pools copied from the shared Lumi Skin generator.
ARABIC_FIRST = ["Fatima", "Mariam", "Aisha", "Noura", "Huda", "Layla", "Reem", "Salma", "Yasmin", "Hessa",
                "Omar", "Khalid", "Ahmed", "Youssef", "Hamdan", "Dana", "Maha", "Abdullah", "Nadia", "Amina",
                "Karim", "Rania", "Zainab", "Latifa"]
ARABIC_LAST = ["Al Mansoori", "Al Hashimi", "Al Suwaidi", "Al Ketbi", "Haddad", "Nasser", "Al Falasi", "Khoury",
               "Saleh", "Al Nuaimi", "Al Marzouqi", "Al Shamsi", "Rahman", "Al Mutairi", "Al Dosari", "Al Harthy",
               "Benali", "El Idrissi", "Mansour", "Hussein", "Bakri", "Al Amiri"]
FRENCH_FIRST = ["Camille", "Chloé", "Léa", "Manon", "Inès", "Julie", "Sophie", "Claire", "Élodie", "Mathilde",
                "Lucas", "Antoine", "Hugo", "Nicolas", "Pauline", "Margaux"]
FRENCH_LAST = ["Martin", "Dubois", "Bernard", "Petit", "Moreau", "Laurent", "Lefèvre", "Girard", "Roux",
               "Fournier", "Mercier", "Blanc", "Garnier", "Faure", "Chevalier"]
ENGLISH_FIRST = ["Emily", "Olivia", "Hannah", "Grace", "Jessica", "Amelia", "Charlotte", "Lucy", "Megan", "James",
                 "Daniel", "Priya", "Anjali", "Rohan", "Maria", "Joy"]
ENGLISH_LAST = ["Carter", "Bennett", "Wright", "Mitchell", "Hughes", "Clarke", "Hayes", "Morgan", "Price",
                "Walker", "Cooper", "Sharma", "Nair", "Mehta", "Santos", "Reyes"]

UAE_CITIES = ["Dubai"] * 5 + ["Abu Dhabi"] * 3 + ["Sharjah"] * 2 + ["Ajman", "Ras Al Khaimah", "Al Ain"]
GCC_CITIES = [("Riyadh", "Saudi Arabia"), ("Jeddah", "Saudi Arabia"), ("Doha", "Qatar"),
              ("Kuwait City", "Kuwait"), ("Manama", "Bahrain"), ("Muscat", "Oman")]
# Extra courier days for some cities, so "delay by city" has a real pattern to find.
SLOW_CITIES = {"Ras Al Khaimah": 2, "Al Ain": 1, "Jeddah": 2, "Muscat": 3}

N_ORDERS = 5000

BESTSELLERS = {"P001": 3, "P009": 3, "P010": 4, "P013": 3, "P025": 4, "P018": 2, "P021": 2}
# Products with more returns, and the usual reason.
RETURN_PROFILE = {
    "P012": (0.10, "skin_reaction"),  # retinol
    "P039": (0.09, "skin_reaction"),  # AHA peel
    "P006": (0.07, "skin_reaction"),  # salicylic cleanser
    "P016": (0.06, "skin_reaction"),  # azelaic acid
    "P027": (0.12, "not_as_described"),  # tinted sun cream: shade mismatch
}
OTHER_REASONS = ["damaged", "wrong_item", "changed_mind", "not_as_described"]
WHITE_FRIDAY = (date(2025, 11, 21), date(2025, 11, 30))  # 20% off everything
RAMADAN_2026 = (date(2026, 2, 18), date(2026, 3, 19))

COMMENTS = {
    "en": {"good": ["Love it, will buy again.", "Great texture and fast delivery.", "My skin feels so much better."],
           "ok": ["It is fine, nothing special.", "Good but a bit pricey."],
           "bad": ["Did not work for my skin.", "Caused irritation, returned it.", "Not as described."]},
    "ar": {"good": ["منتج رائع وسأشتريه مرة أخرى.", "قوام ممتاز وتوصيل سريع."],
           "ok": ["جيد لكن السعر مرتفع قليلاً.", "منتج عادي."],
           "bad": ["لم يناسب بشرتي.", "سبب لي تهيجاً في البشرة."]},
    "fr": {"good": ["J'adore, je rachèterai.", "Texture parfaite, livraison rapide."],
           "ok": ["Correct, sans plus.", "Bien mais un peu cher."],
           "bad": ["Ne convient pas à ma peau.", "Irritation, je l'ai retourné."]},
}

DDL = """
CREATE TABLE products (id TEXT PRIMARY KEY, name TEXT, category TEXT, skin_type TEXT,
    key_ingredients TEXT, price_aed REAL, stock INTEGER);
CREATE TABLE customers (id TEXT PRIMARY KEY, full_name TEXT, email TEXT, phone TEXT, address TEXT,
    city TEXT, country TEXT, language TEXT, signup_date TEXT);
CREATE TABLE orders (order_id TEXT PRIMARY KEY, customer_id TEXT REFERENCES customers(id), order_date TEXT,
    status TEXT, channel TEXT, payment_method TEXT, total_aed REAL, destination_city TEXT,
    destination_country TEXT, promised_date TEXT, shipped_date TEXT, delivered_date TEXT);
CREATE TABLE order_items (order_id TEXT REFERENCES orders(order_id), product_id TEXT REFERENCES products(id),
    qty INTEGER, unit_price_aed REAL);
CREATE TABLE returns (return_id TEXT PRIMARY KEY, order_id TEXT REFERENCES orders(order_id),
    product_id TEXT REFERENCES products(id), qty INTEGER, return_date TEXT, reason TEXT, refund_aed REAL);
CREATE TABLE reviews (review_id TEXT PRIMARY KEY, order_id TEXT REFERENCES orders(order_id),
    product_id TEXT REFERENCES products(id), customer_id TEXT REFERENCES customers(id), rating INTEGER,
    review_date TEXT, comment TEXT);
CREATE INDEX idx_orders_customer ON orders(customer_id);
CREATE INDEX idx_items_order ON order_items(order_id);
"""


def email_slug(name: str) -> str:
    """'Élodie Al Falasi' -> 'elodie.alfalasi'."""
    plain = unicodedata.normalize("NFKD", name).encode("ascii", "ignore").decode().lower()
    first, _, last = plain.partition(" ")
    return f"{first}.{last.replace(' ', '')}"


def load_products() -> list[dict]:
    with PRODUCTS_CSV.open(encoding="utf-8") as file:
        rows = list(csv.DictReader(file))
    for row in rows:
        row["price_aed"] = float(row["price_aed"])
        row["stock"] = int(row["stock"])
    return rows


def make_customers(rng: random.Random) -> list[dict]:
    pools = [(ARABIC_FIRST, ARABIC_LAST, "arabic"), (ENGLISH_FIRST, ENGLISH_LAST, "english"),
             (FRENCH_FIRST, FRENCH_LAST, "french")]
    phones = rng.sample(range(10000), N_CUSTOMERS)
    used_emails: dict[str, int] = {}
    customers = []
    for index in range(N_CUSTOMERS):
        firsts, lasts, pool = rng.choices(pools, weights=[45, 28, 27])[0]
        name = f"{rng.choice(firsts)} {rng.choice(lasts)}"
        slug = email_slug(name)
        used_emails[slug] = used_emails.get(slug, 0) + 1
        suffix = "" if used_emails[slug] == 1 else str(used_emails[slug])
        if rng.random() < 0.2:
            city, country = rng.choice(GCC_CITIES)
        else:
            city, country = rng.choice(UAE_CITIES), "United Arab Emirates"
        if pool == "arabic":
            language = rng.choices(["ar", "en", "fr"], weights=[75, 15, 10])[0]
        elif pool == "french":
            language = rng.choices(["fr", "en"], weights=[85, 15])[0]
        else:
            language = "en"
        # 30% signed up before the order history starts; the rest during it.
        if rng.random() < 0.3:
            signup = date(2024, 10, 1) + timedelta(days=rng.randint(0, 181))
        else:
            signup = START + timedelta(days=rng.randint(0, (SNAPSHOT - START).days - 14))
        customers.append({
            "id": f"C{index + 1:04d}", "full_name": name, "email": f"{slug}{suffix}@example.com",
            "phone": f"+971 50 000 {phones[index]:04d}",
            "address": f"Building {rng.randint(1, 99)}, Street {rng.randint(1, 40)}, {city}",
            "city": city, "country": country, "language": language, "signup_date": signup.isoformat(),
        })
    return customers


def day_weight(day: date) -> float:
    """Demand on a given day: growth over time plus seasonal peaks."""
    progress = (day - START).days / (SNAPSHOT - START).days
    weight = 1.0 + 0.8 * progress  # the shop grows
    if WHITE_FRIDAY[0] <= day <= WHITE_FRIDAY[1]:
        weight *= 3.0
    elif day.month == 12:
        weight *= 1.3
    elif RAMADAN_2026[0] <= day <= RAMADAN_2026[1]:
        weight *= 1.4
    elif day.month in (7, 8):
        weight *= 0.8  # summer travel dip
    return weight


def make_orders(rng: random.Random, customers: list[dict], products: list[dict]):
    """Pick a day for each order (by demand), then a customer who had signed up by then.

    Each customer gets a "loyalty" weight: most buy once or twice, a few buy often,
    and about 8% never buy. That gives a realistic repeat-customer pattern.
    """
    days = [START + timedelta(days=i) for i in range((SNAPSHOT - START).days + 1)]
    order_days = sorted(rng.choices(days, weights=[day_weight(day) for day in days], k=N_ORDERS))

    by_signup = sorted(customers, key=lambda c: (c["signup_date"], c["id"]))
    cumulative, running = [], 0.0
    for _ in by_signup:
        running += 0.0 if rng.random() < 0.08 else rng.lognormvariate(0, 0.6)
        cumulative.append(running)

    orders, items = [], []
    eligible = 0  # by_signup[:eligible] had signed up on or before the order day
    for number, order_day in enumerate(order_days, start=10001):
        while eligible < len(by_signup) and by_signup[eligible]["signup_date"] <= order_day.isoformat():
            eligible += 1
        customer = rng.choices(by_signup[:eligible], cum_weights=cumulative[:eligible])[0]
        order_id = f"LS-{number}"
        lines = make_lines(rng, order_id, order_day, products)
        items.extend(lines)
        orders.append(make_order(rng, order_id, order_day, customer, lines))
    return orders, items


def make_lines(rng: random.Random, order_id: str, order_day: date, products: list[dict]) -> list[dict]:
    summer = order_day.month in (4, 5, 6, 7, 8, 9)
    weights = [BESTSELLERS.get(p["id"], 1) * (1.5 if summer and p["category"] == "sunscreen" else 1)
               for p in products]
    n_lines = rng.choices([1, 2, 3, 4], weights=[50, 30, 14, 6])[0]
    chosen: list[dict] = []
    while len(chosen) < n_lines:
        product = rng.choices(products, weights=weights)[0]
        if product not in chosen:
            chosen.append(product)
    discount = 0.8 if WHITE_FRIDAY[0] <= order_day <= WHITE_FRIDAY[1] else 1.0
    return [{"order_id": order_id, "product_id": p["id"], "qty": rng.choices([1, 2, 3], weights=[85, 12, 3])[0],
             "unit_price_aed": round(p["price_aed"] * discount, 2)} for p in chosen]


def make_order(rng: random.Random, order_id: str, order_day: date, customer: dict, lines: list[dict]) -> dict:
    total = round(sum(line["qty"] * line["unit_price_aed"] for line in lines), 2)
    progress = (order_day - START).days / (SNAPSHOT - START).days
    channel = rng.choices(["website", "app", "instagram"], weights=[55 - 20 * progress, 25 + 20 * progress, 20])[0]
    payment = "cod" if total <= 1000 and rng.random() < 0.3 else "card"
    uae = customer["country"] == "United Arab Emirates"
    promised = order_day + timedelta(days=3 if uae else 7)
    order = {
        "order_id": order_id, "customer_id": customer["id"], "order_date": order_day.isoformat(),
        "status": "cancelled", "channel": channel, "payment_method": payment, "total_aed": total,
        "destination_city": customer["city"], "destination_country": customer["country"],
        "promised_date": promised.isoformat(), "shipped_date": None, "delivered_date": None,
    }
    if rng.random() < 0.04:
        return order  # cancelled before shipping

    shipped = order_day + timedelta(days=rng.randint(0, 1))
    transit = rng.randint(1, 3) if uae else rng.randint(3, 7)
    transit += SLOW_CITIES.get(customer["city"], 0) * (rng.random() < 0.5)
    if rng.random() < 0.10:
        transit += rng.randint(1, 4)  # random courier problem
    if WHITE_FRIDAY[0] <= order_day <= date(2025, 12, 5):
        transit += rng.randint(1, 3)  # peak-season backlog
    delivered = shipped + timedelta(days=transit)

    if shipped > SNAPSHOT:
        order["status"] = "processing"
    elif delivered > SNAPSHOT:
        order.update(status="shipped", shipped_date=shipped.isoformat())
    else:
        order.update(status="delivered", shipped_date=shipped.isoformat(), delivered_date=delivered.isoformat())
    return order


def make_returns_and_reviews(rng: random.Random, orders: list[dict], items: list[dict], customers: list[dict]):
    language = {c["id"]: c["language"] for c in customers}
    quality = {f"P{i:03d}": 3.6 + rng.random() * 1.1 for i in range(1, 41)}
    lines_by_order: dict[str, list[dict]] = {}
    for line in items:
        lines_by_order.setdefault(line["order_id"], []).append(line)

    returns, reviews = [], []
    for order in orders:
        if order["status"] != "delivered":
            continue
        delivered = date.fromisoformat(order["delivered_date"])
        returned_lines = 0
        for line in lines_by_order[order["order_id"]]:
            rate, reason = RETURN_PROFILE.get(line["product_id"], (0.03, None))
            if order["destination_country"] != "United Arab Emirates":
                rate += 0.02  # longer trips, more damage
            return_day = delivered + timedelta(days=rng.randint(1, 14))
            is_returned = rng.random() < rate and return_day <= SNAPSHOT
            if is_returned:
                returned_lines += 1
                returns.append({
                    "return_id": f"R{len(returns) + 1:04d}", "order_id": order["order_id"],
                    "product_id": line["product_id"], "qty": line["qty"], "return_date": return_day.isoformat(),
                    "reason": reason if reason and rng.random() < 0.7 else rng.choice(OTHER_REASONS),
                    "refund_aed": round(line["qty"] * line["unit_price_aed"], 2),
                })
            review_day = delivered + timedelta(days=rng.randint(2, 20))
            if review_day <= SNAPSHOT and rng.random() < (0.5 if is_returned else 0.22):
                mean = 2.0 if is_returned else quality[line["product_id"]]
                rating = min(5, max(1, round(rng.gauss(mean, 0.8))))
                mood = "good" if rating >= 4 else "ok" if rating == 3 else "bad"
                reviews.append({
                    "review_id": f"V{len(reviews) + 1:04d}", "order_id": order["order_id"],
                    "product_id": line["product_id"], "customer_id": order["customer_id"], "rating": rating,
                    "review_date": review_day.isoformat(),
                    "comment": rng.choice(COMMENTS[language[order["customer_id"]]][mood]),
                })
        if returned_lines == len(lines_by_order[order["order_id"]]):
            order["status"] = "returned"  # every item came back
    return returns, reviews


def check_totals(orders: list[dict], items: list[dict]) -> None:
    """Stop if any order total differs from the sum of its lines."""
    sums: dict[str, float] = {}
    for line in items:
        sums[line["order_id"]] = sums.get(line["order_id"], 0) + line["qty"] * line["unit_price_aed"]
    bad = [o["order_id"] for o in orders if abs(o["total_aed"] - sums[o["order_id"]]) > 0.01]
    if bad:
        raise ValueError(f"{len(bad)} orders do not match their lines, e.g. {bad[:3]}")


def write_db(path: Path, tables: dict[str, list[dict]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.unlink(missing_ok=True)
    conn = sqlite3.connect(path)
    conn.executescript(DDL)
    for table, rows in tables.items():
        columns = list(config.SCHEMA[table]["columns"])
        placeholders = ", ".join("?" for _ in columns)
        conn.executemany(f"INSERT INTO {table} ({', '.join(columns)}) VALUES ({placeholders})",
                         [[row[c] for c in columns] for row in rows])
    conn.commit()
    conn.close()


def generate(out_path: Path = config.DB_PATH) -> dict[str, int]:
    rng = random.Random(SEED)
    products = load_products()
    customers = make_customers(rng)
    orders, items = make_orders(rng, customers, products)
    check_totals(orders, items)
    returns, reviews = make_returns_and_reviews(rng, orders, items, customers)
    tables = {"products": products, "customers": customers, "orders": orders, "order_items": items,
              "returns": returns, "reviews": reviews}
    write_db(Path(out_path), tables)
    return {table: len(rows) for table, rows in tables.items()}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out", type=Path, default=config.DB_PATH)
    args = parser.parse_args()
    counts = generate(args.out)
    print(f"Wrote {args.out}: " + ", ".join(f"{table}={n}" for table, n in counts.items()))


if __name__ == "__main__":
    main()
